-- Insert sample properties
INSERT INTO public.properties (name, address, city, state, country, description, property_type, total_value, share_price, total_shares, available_shares, annual_return_rate, thumbnail_url, status)
VALUES 
  (
    'Downtown Toronto Condo',
    '123 King Street West',
    'Toronto',
    'ON',
    'Canada',
    'Luxury 2-bedroom condominium in the heart of downtown Toronto. Walking distance to financial district, entertainment, and transit. Premium finishes throughout with stunning city views. This property offers excellent rental income potential with high occupancy rates in one of Canada''s most desirable urban locations.',
    'residential',
    850000.00,
    85.00,
    10000,
    7500,
    8.5,
    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
    'active'
  ),
  (
    'Vancouver Tech Hub Office',
    '456 Granville Street',
    'Vancouver',
    'BC',
    'Canada',
    'Class A office space in Vancouver''s thriving tech corridor. Fully leased to established tech companies with long-term agreements. Modern amenities and LEED certified building. Prime location with excellent transit access and surrounded by restaurants and retail.',
    'commercial',
    2500000.00,
    125.00,
    20000,
    12000,
    9.2,
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800',
    'active'
  ),
  (
    'Montreal Mixed-Use Development',
    '789 Rue Sainte-Catherine',
    'Montreal',
    'QC',
    'Canada',
    'Prime mixed-use property featuring retail on ground floor and residential units above. Located in bustling shopping district with high foot traffic. Recently renovated with modern infrastructure. Strong tenant mix providing stable income streams.',
    'mixed',
    1200000.00,
    60.00,
    20000,
    15000,
    7.8,
    'https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=800',
    'active'
  ),
  (
    'Calgary Industrial Warehouse',
    '321 Industrial Boulevard',
    'Calgary',
    'AB',
    'Canada',
    'Modern logistics warehouse with excellent highway access. Long-term lease with national distribution company. Triple net lease structure providing stable returns. 50,000 sq ft facility with loading docks and office space.',
    'industrial',
    3200000.00,
    80.00,
    40000,
    25000,
    10.5,
    'https://images.unsplash.com/photo-1553246969-7dcb4259a87b?w=800',
    'active'
  ),
  (
    'Ottawa Government District Office',
    '555 Wellington Street',
    'Ottawa',
    'ON',
    'Canada',
    'Premium office building in Ottawa''s government district. Stable government tenants with excellent credit. Recently renovated common areas and upgraded building systems. Walking distance to Parliament Hill and major attractions.',
    'commercial',
    4500000.00,
    150.00,
    30000,
    8000,
    7.2,
    'https://images.unsplash.com/photo-1577495508048-b635879837f1?w=800',
    'active'
  ),
  (
    'Halifax Waterfront Retail',
    '100 Lower Water Street',
    'Halifax',
    'NS',
    'Canada',
    'Charming retail property on Halifax''s famous waterfront. Mix of restaurant and boutique retail tenants. Strong tourism and local traffic year-round. Historic building with modern amenities and stunning harbor views.',
    'commercial',
    950000.00,
    47.50,
    20000,
    18000,
    8.0,
    'https://images.unsplash.com/photo-1555636222-cae831e670b3?w=800',
    'coming_soon'
  ),
  (
    'Edmonton Residential Complex',
    '200 Jasper Avenue',
    'Edmonton',
    'AB',
    'Canada',
    'Modern multi-family residential complex with 48 units. Mix of 1 and 2 bedroom apartments with in-suite laundry. Underground parking and fitness center. Located near University of Alberta with strong rental demand.',
    'residential',
    6500000.00,
    65.00,
    100000,
    75000,
    8.8,
    'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
    'active'
  ),
  (
    'Winnipeg Retail Plaza',
    '350 Portage Avenue',
    'Winnipeg',
    'MB',
    'Canada',
    'Well-established retail plaza with national anchor tenants. High visibility location on major arterial road. Recently upgraded parking lot and signage. Stable cash flow with long-term leases in place.',
    'commercial',
    2100000.00,
    70.00,
    30000,
    22000,
    7.5,
    'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800',
    'active'
  );
